# services/git_service.py
from typing import List, Dict, Optional
from pydantic import BaseModel
import httpx
from ..config import settings
from ..utils.logger import logger

class GitFile(BaseModel):
    path: str
    content: str
    mode: str = "100644"

class GitService:
    def __init__(self, owner: Optional[str] = None, repo: Optional[str] = None, pat: Optional[str] = None):
        self.owner = owner or settings.GITHUB_OWNER
        self.repo = repo or settings.GITHUB_REPO
        self.pat = pat or settings.GITHUB_PAT
        self.base_url = "https://api.github.com"
        
        if not all([self.owner, self.repo, self.pat]):
            logger.warning("GitHub credentials not fully configured - GitService will fail on commit")
        
        self.headers = {
            "Authorization": f"token {self.pat}",
            "Accept": "application/vnd.github.v3+json",
            "User-Agent": "AI-Office-Bot/1.0"
        }
    
    async def _request(self, method: str, endpoint: str, **kwargs) -> httpx.Response:
        """Wrapper para requests com logging"""
        url = f"{self.base_url}/{endpoint}"
        async with httpx.AsyncClient() as client:
            resp = await client.request(method, url, headers=self.headers, **kwargs)
            logger.debug("GitHub API call", method=method, endpoint=endpoint, status=resp.status_code)
            resp.raise_for_status()
            return resp
    
    async def commit_and_create_pr(
        self,
        branch: str,
        files: List[GitFile],
        commit_msg: str,
        task_id: str
    ) -> Dict[str, str]:
        """Cria branch, commita arquivos e abre PR via GitHub API"""
        if not all([self.owner, self.repo, self.pat]):
            raise RuntimeError("GitHub credentials not configured")
        
        # 1. Get main branch SHA
        resp = await self._request("GET", f"repos/{self.owner}/{self.repo}/git/ref/heads/main")
        main_sha = resp.json()["object"]["sha"]
        
        # 2. Create branch (se não existir)
        try:
            await self._request("POST", f"repos/{self.owner}/{self.repo}/git/refs", 
                              json={"ref": f"refs/heads/{branch}", "sha": main_sha})
        except httpx.HTTPStatusError as e:
            if e.response.status_code != 422:  # 422 = branch já existe
                raise
        
        # 3. Create blobs + tree
        tree_items = []
        for file in files:
            blob_resp = await self._request("POST", f"repos/{self.owner}/{self.repo}/git/blobs",
                                          json={"content": file.content, "encoding": "utf-8"})
            tree_items.append({
                "path": file.path,
                "mode": file.mode,
                "type": "blob",
                "sha": blob_resp.json()["sha"]
            })
        
        tree_resp = await self._request("POST", f"repos/{self.owner}/{self.repo}/git/trees",
                                      json={"tree": tree_items, "base_tree": main_sha})
        tree_sha = tree_resp.json()["sha"]
        
        # 4. Create commit
        commit_resp = await self._request("POST", f"repos/{self.owner}/{self.repo}/git/commits",
                                        json={"message": commit_msg, "tree": tree_sha, "parents": [main_sha]})
        commit_sha = commit_resp.json()["sha"]
        
        # 5. Update branch ref
        await self._request("PATCH", f"repos/{self.owner}/{self.repo}/git/refs/heads/{branch}",
                          json={"sha": commit_sha, "force": False})
        
        # 6. Create PR
        pr_resp = await self._request("POST", f"repos/{self.owner}/{self.repo}/pulls",
                                    json={
                                        "title": f"[{task_id}] {commit_msg}",
                                        "body": f"🤖 Auto-generated by AI Office\n\nTask: [[{task_id}]]\n\n> Review and merge when ready.",
                                        "head": branch,
                                        "base": "main",
                                        "draft": True  # Começa como draft para revisão
                                    })
        pr_data = pr_resp.json()
        
        logger.info("PR created", task_id=task_id, pr_url=pr_data["html_url"], branch=branch)
        
        return {
            "pr_url": pr_data["html_url"],
            "pr_number": str(pr_data["number"]),
            "commit_sha": commit_sha[:7],
            "branch": branch,
            "status": "draft"
        }
    
    async def update_pr_status(self, pr_number: str, draft: bool = False) -> Dict:
        """Marca PR como ready for review"""
        resp = await self._request("PATCH", f"repos/{self.owner}/{self.repo}/pulls/{pr_number}",
                                 json={"draft": draft})
        data = resp.json()
        logger.info("PR status updated", pr_number=pr_number, draft=draft)
        return {"pr_url": data["html_url"], "status": "ready" if not draft else "draft"}